# Lines on each section of this file should be sorted alphabetically

[versions]
# https://developer.android.com/studio/releases/gradle-plugin
android-gradle-plugin = "8.7.1"
android-sdk = "33"
android-minsdk = "23"

androidx-appcompat = "1.6.1"
# Compose 1.6.8 - https://developer.android.com/develop/ui/compose/bom/bom-mapping
androidx-compose = "2023.06.01"
androidx-navigation = "2.5.3"
androidx-test-ext = "1.1.5"
webkit = "1.7.0"
datastorePreferences = "1.0.0"
ditto = "4.11.6"

junit = "4.13.2"
kotlin-gradle-plugin = "1.9.25"
androidComposeKotlinCompiler = "1.5.15"
core-ktx = "1.9.0"
espresso-core = "3.5.1"
material = "1.10.0"

gradle-wrapper = "8.10.2"
kotlin = "1.9.25"
jreleaser = "1.20.0"

[libraries]
androidx-appcompat-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-compose-composeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-runtime-runtimeLivedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-compose-ui-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose" }
androidx-navigation-navigationCompose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext" }
live-ditto-ditto = { group = "live.ditto", name = "ditto", version.ref = "ditto" }
junit-junit = { group = "junit", name = "junit", version.ref = "junit" }
joda-time-joda-time = { group = "joda-time", name = "joda-time", version = "2.10.10" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-gradle-plugin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser"}